################################################################################
# Add-on: HAOS Kiosk Display (haoskiosk)
# File: xorg.conf
# Version: 1.3.1
# Originally by Jeff Kosowsky, maintained by William Fayers
# Date: April 2026
#
# Includes option to select FBDEV0 (framebuffer 0 or /dev/fb0) or
# FBDEV1 (framebuffer 1 or /dev/fb1) which should correspond with
# HDMI1 and HDMI2 video outputs.
# Unfortunately, current HAOS implementation on RPi mirrors all output on both
# HDMI1 and HDMI2 (including console output) so doesn't make a difference.
# NOTE: Ideally one would keep console on HDMI1 and run X on HDMI2
# to avoid conflict and over-writing
################################################################################

Section "ServerFlags"
    Option "AutoAddDevices" "on"
    Option "AutoEnableDevices" "on"
EndSection

Section "Device"
    Identifier    "FBDEV0"
    Driver        "fbdev"
    Option        "fbdev"  "/dev/fb0"
EndSection

Section "Device"
    Identifier    "FBDEV1"
    Driver        "fbdev"
    Option        "fbdev"  "/dev/fb1"
EndSection

Section "Screen"
    Identifier    "Screen0"
    Device        "FBDEV0"
EndSection

Section "Screen"
    Identifier    "Screen1"
    Device        "FBDEV1"
EndSection

Section "InputClass"
    Identifier "Touchscreen"
    MatchIsTouchscreen "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "on"
EndSection

Section "InputClass"
    Identifier "Touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "on"
    Option "ScrollMethod" "twofinger"
EndSection
